include ../../../htx.mk

TARGET= \
	default hxecapi.readme

.PHONY: all clean

all: ${TARGET}
	${MKDIR} ${REGRULES}/hxecapi/
	${CP} ${TARGET} ${REGRULES}/hxecapi/ 

clean:
	${RM} -rf ${REGRULES}/hxecapi/* 
