#!/bin/bash

proc_ver=`cat ${HTX_LOG_DIR}/htx_syscfg | grep Version | awk -F: '{print $2}'`
proc_ver_dec=`printf %d $proc_ver`
P6Compatmode=`cat ${HTX_LOG_DIR}/htx_syscfg | grep -i Power6Compatmode | awk -F: '{print $2}'|sed -e 's/^ *//' `

if [[ $proc_ver_dec -ge 63 && $P6Compatmode = "False" ]] # Shifts for P7 & above
then
	if [[ $proc_ver_dec -ge 78 ]]
	then
    	create_my_mdt mem:default.mfg 							> ${HTXMDT}/mdt.mem_inter_node
		rule="default.inter_node"
		device="fabn"
        mdt="mdt.mem_inter_node"
        echo "Creating mdt.mem_inter_node"
	else
        # Print the memory configure
        ${HTXBIN}/hxefabricbus  /dev/ablink OTH ${HTXREGRULES}/hxefabricbus/default.ab query_memconf >/dev/null 2>&1
		create_my_mdt mem:memmfg 								> ${HTXMDT}/mdt.ab_mem
		rule="default.ab"
		device="ablink"
        mdt="mdt.ab_mem"
        echo "Creating mdt.ab_mem ..."
	fi
else
    cat ${HTXMDT}/mdt.mem  							> ${HTXMDT}/mdt.ab_mem
	rule="default.ab"
    device="ablink"
    mdt="mdt.ab_mem"
    echo "Creating mdt.ab_mem ..."
fi
echo 											>> ${HTXMDT}/${mdt}
echo "$device:"										>> ${HTXMDT}/${mdt}
echo -e "\tHE_name = \"hxefabricbus\"                	"				>> ${HTXMDT}/${mdt}
echo -e "\tadapt_desc = \"Node to Node\"            	"				>> ${HTXMDT}/${mdt}
echo -e "\tdevice_desc = \"Memory BW\"              	"				>> ${HTXMDT}/${mdt}
echo -e "\treg_rules = \"hxefabricbus/$rule\"        "                          	>> ${HTXMDT}/${mdt}
echo -e "\temc_rules = \"hxefabricbus/$rule\"        "                          	>> ${HTXMDT}/${mdt}
echo -e "\tcont_on_err = \"NO\" 	"						   	>> ${HTXMDT}/${mdt}
echo 											>> ${HTXMDT}/${mdt}
