#!/bin/bash

proc_ver=`cat ${HTX_LOG_DIR}/htx_syscfg | grep Version | awk -F: '{print $2}'`
proc_ver_dec=`printf %d $proc_ver`

if [[ $proc_ver_dec -ge 78 ]]
then
	rule="default.inter_node"
	device="fabn"
	mdt="mdt.inter_node"
	echo "Creating mdt.inter_node..."
else
	# Print the memory configure
	${HTXBIN}/hxefabricbus  /dev/ablink OTH ${HTXREGRULES}/hxefabricbus/default.ab query_memconf >/dev/null 2>&1

	# Print the mask configure
	${HTXBIN}/hxefabricbus /dev/ablink OTH ${HTXREGRULES}/hxefabricbus/default.ab query_maskconf >/dev/null 2>&1

	rule="default.ab"
	device="ablink"
	mdt="mdt.ablink"
	echo "Creating mdt.ablink ..."
fi

cat ${HTXMDT}mdt.all | create_mdt_with_devices.awk                                              > ${HTXMDT}${mdt}

echo                                                                                            >> ${HTXMDT}/${mdt}
echo "${device}:"                                                                                  >> ${HTXMDT}/${mdt}
echo -e "\tHE_name = \"hxefabricbus\"                     "     					>> ${HTXMDT}/${mdt}
echo -e "\tadapt_desc = \"Node to Node\"                  "    					>> ${HTXMDT}/${mdt}
echo -e "\tdevice_desc = \"Memory BW\"                    "     					>> ${HTXMDT}/${mdt}
echo -e "\treg_rules = \"hxefabricbus/$rule\"        "                          		>> ${HTXMDT}/${mdt}
echo -e "\temc_rules = \"hxefabricbus/$rule\"        "                          		>> ${HTXMDT}/${mdt}
echo -e "\tcont_on_err = \"NO\"     			"                                       >> ${HTXMDT}/${mdt}
echo                                                                                       	>> ${HTXMDT}/${mdt}

