#!/bin/bash

proc_ver=`cat ${HTX_LOG_DIR}/htx_syscfg | grep Version | awk -F: '{print $2}'`
proc_ver_dec=`printf %d $proc_ver`

mdt="mdt.mem_inter_node"
rule="default.inter_node"
device="fabn"
echo "Creating mdt.mem_inter_node"

if [[ $proc_ver_dec -ge 78 ]]
then
    create_my_mdt mem:default.mfg 							> ${HTXMDT}/${mdt}
else
    create_my_mdt mem:memmfg 								> ${HTXMDT}/${mdt}
fi

echo 											>> ${HTXMDT}/${mdt}
echo "$device:"										>> ${HTXMDT}/${mdt}
echo -e "\tHE_name = \"hxefabricbus\"                	"				>> ${HTXMDT}/${mdt}
echo -e "\tadapt_desc = \"Node to Node\"            	"				>> ${HTXMDT}/${mdt}
echo -e "\tdevice_desc = \"Memory BW\"              	"				>> ${HTXMDT}/${mdt}
echo -e "\treg_rules = \"hxefabricbus/$rule\"        "                          	>> ${HTXMDT}/${mdt}
echo -e "\temc_rules = \"hxefabricbus/$rule\"        "                          	>> ${HTXMDT}/${mdt}
echo -e "\tcont_on_err = \"NO\" 	"						   	>> ${HTXMDT}/${mdt}
echo 											>> ${HTXMDT}/${mdt}
