#!/bin/bash

rule="default.inter_chip"
device="fabc"
mdt="mdt.inter_chip"
echo "Creating mdt.inter_chip..."

cat ${HTXMDT}mdt.all | create_mdt_with_devices.awk                                              > ${HTXMDT}/${mdt}

echo                                                                                            >> ${HTXMDT}/${mdt}
echo "${device}:"                                                                                  >> ${HTXMDT}/${mdt}
echo -e "\tHE_name = \"hxefabricbus\"                     "                         >> ${HTXMDT}/${mdt}
echo -e "\tadapt_desc = \"Node to Node\"                  "                     >> ${HTXMDT}/${mdt}
echo -e "\tdevice_desc = \"Memory BW\"                    "                         >> ${HTXMDT}/${mdt}
echo -e "\treg_rules = \"hxefabricbus/$rule\"        "                                  >> ${HTXMDT}/${mdt}
echo -e "\temc_rules = \"hxefabricbus/$rule\"        "                                  >> ${HTXMDT}/${mdt}
echo -e "\tcont_on_err = \"NO\"                 "                                       >> ${HTXMDT}/${mdt}
echo                                                                                        >> ${HTXMDT}/${mdt}

