#!/bin/ksh

# IBM_PROLOG_BEGIN_TAG
#
# Copyright 2003,2016 IBM International Business Machines Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#                http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# IBM_PROLOG_END_TAG

#################################
# function create_mdt starts here
#################################
create_mdt()
{
    echo " [$script_name]: Creating Equaliser mdt file $2 " | tee -a $HTXNoise
    ${HTXPATH}/bin/create_eq_mdt $1 $2
    echo " Backing up Equaliser config and mdt file in /tmp"
    cp $1 /tmp/
    cp $2 /tmp/
}

for file in `/bin/ls $HTXCFGPATH/[a-zA-Z]*.cfg 2>/dev/null`
do
    file_name=`basename $file`
    suffix=`echo $file_name| sed "s/htx_//" | sed "s/\.cfg//"`
    mdt_name=mdt.$suffix
    create_mdt ${HTXCFGPATH}/$file_name ${HTXMDT}/$mdt_name
done

