#!/bin/bash

# @(#)89        1.4  src/htx/usr/lpp/htx/etc/scripts/create_mdt_xyz, exer_ablink, htxltsbml 1/1/09 23:47:16

true_pvr=`grep "TRUE PVR ver" ${HTX_LOG_DIR}/htx_syscfg | awk -F: '{print $2}'`
true_pvr=`printf %d $true_pvr`

max_chips_per_node=`grep "Chips in node" ${HTX_LOG_DIR}/htx_syscfg | cut -d '(' -f 2 | cut -d ')' -f 1 | sort -n -r | awk '(NR==1)'`
max_chips_dec=`printf %d $max_chips_per_node`

if [[ $max_chips_dec -le 1 ]]
then 
	echo "create_mdt_xyz:No node found with chips > 1,max_chips_dec = $max_chips_dec, mdt.inter_chip will not be created." >> $HTXNoise
	exit
fi	

if [[ $true_pvr -ge 78 ]]
then
    rule="default.inter_chip"
    device="fabc"
    mdt="mdt.inter_chip"
    echo "Creating mdt.inter_chip..."
else
	# Print the memory configure
	${HTXBIN}/hxefabricbus  /dev/ablink OTH ${HTXREGRULES}/hxefabricbus/default.xyz query_memconf > /dev/null 2>&1

	# Print the memory configure
	${HTXBIN}/hxefabricbus  /dev/ablink OTH ${HTXREGRULES}/hxefabricbus/default.xyz query_maskconf > /dev/null 2>&1

	rule="default.xyz"
	device="xyzlink"
	mdt="mdt.xyzlink"
	echo "Creating mdt.xyzlink ..."
fi

cat ${HTXMDT}mdt.all | create_mdt_with_devices.awk                                              > ${HTXMDT}/${mdt}

echo                                                                                            >> ${HTXMDT}/${mdt}
echo "${device}:"                                                                                  >> ${HTXMDT}/${mdt}
echo -e "\tHE_name = \"hxefabricbus\"                     "                         >> ${HTXMDT}/${mdt}
echo -e "\tadapt_desc = \"Node to Node\"                  "                     >> ${HTXMDT}/${mdt}
echo -e "\tdevice_desc = \"Memory BW\"                    "                         >> ${HTXMDT}/${mdt}
echo -e "\treg_rules = \"hxefabricbus/$rule\"        "                                  >> ${HTXMDT}/${mdt}
echo -e "\temc_rules = \"hxefabricbus/$rule\"        "                                  >> ${HTXMDT}/${mdt}
echo -e "\tcont_on_err = \"NO\"                 "                                       >> ${HTXMDT}/${mdt}
echo                                                                                        >> ${HTXMDT}/${mdt}

