#!/bin/bash
# IBM_PROLOG_BEGIN_TAG
#
# Copyright 2003,2016 IBM International Business Machines Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# IBM_PROLOG_END_TAG

true_pvr=` grep "TRUE PVR ver" ${HTX_LOG_DIR}/htx_syscfg | awk -F: '{print $2}'`
true_pvr=`printf %d $true_pvr`

num_nodes=`grep "Number of nodes" ${HTX_LOG_DIR}/htx_syscfg | awk -F: '{print $2}'`
num_nodes_dec=`printf %d $num_nodes`

if [[ $num_nodes_dec -le 1 ]]
then
    echo "create_ab_mem_mdt:number of nodes found to be <= 1,num_nodes_dec = $num_nodes_dec, mdt.mem_inter_node will not be created." >> $HTXNoise
    exit
fi

mdt="mdt.mem_inter_node"
rule="default.inter_node"
device="fabn"
echo "Creating mdt.mem_inter_node"

if [[ $true_pvr -ge 78 ]]
then
    create_my_mdt mem:default.mfg 							> ${HTXMDT}/${mdt}
else
    create_my_mdt mem:memmfg 								> ${HTXMDT}/${mdt}
fi

echo 											>> ${HTXMDT}/${mdt}
echo "$device:"										>> ${HTXMDT}/${mdt}
echo -e "\tHE_name = \"hxefabricbus\"                	"				>> ${HTXMDT}/${mdt}
echo -e "\tadapt_desc = \"Node to Node\"            	"				>> ${HTXMDT}/${mdt}
echo -e "\tdevice_desc = \"Memory BW\"              	"				>> ${HTXMDT}/${mdt}
echo -e "\treg_rules = \"hxefabricbus/$rule\"        "                          	>> ${HTXMDT}/${mdt}
echo -e "\temc_rules = \"hxefabricbus/$rule\"        "                          	>> ${HTXMDT}/${mdt}
echo -e "\tcont_on_err = \"NO\" 	"						   	>> ${HTXMDT}/${mdt}
echo 											>> ${HTXMDT}/${mdt}
