#!/bin/bash

# IBM_PROLOG_BEGIN_TAG
#
# Copyright 2003,2016 IBM International Business Machines Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#                http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# IBM_PROLOG_END_TAG
########################################################


# This program takes PID of an exerciser and cleanup IPC resources if the any present

_DEBUG_MODE_=0


usage()
{
	echo "usage: $0 <pid>"
}

DEBUG_INFO()
{
	if [ ${_DEBUG_MODE_} -eq 1 ] ; then
		echo "$*"
	fi
	if [ ${_DEBUG_MODE_} -eq 2 ] ; then
		echo "$*" >> /tmp/htx_ipcs_cleanup.out
	fi
}

if [ $# -ne 1 ] ; then
	usage;
	exit 1;
fi

#saving command line argument
exer_pid=$1

#check for any IPC resource
ipc_count=`ipcs -m -p | awk '$3 == "'$exer_pid'" ' | wc -l`
if [ ${ipc_count} -eq 0 ] ; then
	DEBUG_INFO "no IPC resource found for provided process id $exer_pid, exiting..." 	
	exit 2;
fi

#cleaning up shared memory
ipc_count=`ipcs -m -p | awk '$3 == "'$exer_pid'" ' | wc -l`
if [ ${ipc_count} -ne 0 ] ; then
	DEBUG_INFO "going to delete shared memory of process id ${exer_pid}"
	id_list=`ipcs -m -p | awk -v pid_var="$exer_pid" 'pid_var==$3 {print $1}' `
	for id in ${id_list} ; do
		DEBUG_INFO "deleting shared memory id $id"
		ipcrm -m $id
	done
fi

DEBUG_INFO "IPC cleanup is done, exiting.."
