#!/bin/bash

# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# 		 http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# IBM_PROLOG_END_TAG
########################################################

# stopping HTXD daemon
htxd_path="`cat /var/log/htx_install_path 2>/dev/null`/bin/htxd"
htxd_pid=$(ps -aef | grep "$htxd_path" | grep -v grep | awk '$3 == 1 {print $2}')
if [ -z "$htxd_pid" ] ; then
	echo "htxd is already exited..."
	exit 0
else
	echo "stopping htxd with pid:$htxd_pid..."
	kill -15 $htxd_pid
fi


# waiting for all process to exit
process_count=1;
while [ "$process_count"  -ne 0 ]
do
	sleep 1
	process_count=$(ps -aef | grep -e $htxd_pid | grep -v grep | wc -l)
	exerciser_count=$(ps -aef | grep -e hxe | grep -v grep | wc -l)
	echo "remaining exerciser count : $exerciser_count" 
done

echo "all htx processes are exited..."
echo "htxd is stopped"

exit 0

