#!/bin/ksh

# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# 		 http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# IBM_PROLOG_END_TAG
#
# COMPONENT_NAME: htxd
#
###############################################################################
###############################################################################
##
##  bootme:  setup Linux system to automatically load and run htx on reboot
##
###############################################################################


# THERE IS NOTHING TO EDIT IN THIS FILE
# TO CHANGE BOOTME CONFIG GO TO: ${HTX_HOME_DIR}/rules/reg/bootme/default


###############################################################################
###############################################################################
return_value()
{
	echo $1; exit $1;
}
###############################################################################

###############################################################################
usage()
{
	echo "Error: $1 should be run from 'htxcmdline -bootme' command"
	return_value 51
}
###############################################################################

###############################################################################
htxd_bootme_on ()
{

# Check for free space in directories likely to cause problems if full
	check_space "/tmp" 10
	check_space "/var" 10

# create crontab entry
# Add crontab entry to cause system to run bootmeStuff
	CRONENTRY="`cat /etc/crontab | grep bootme`"
	if [ "$CRONENTRY" == ""  ]; then
		cp /etc/crontab /etc/crontab.ORIG
		bootmeStuff=${HTX_HOME_DIR}/etc/scripts/bootmeStuff
		if [ -z ${BOOT_CMD_FOUND} ] ; then
			echo "$REBOOT * * *  root $bootmeStuff >/dev/null 2>&1 &" >>/etc/crontab
		else
			echo "$REBOOT * * * root $bootmeStuff ${BOOT_CMD_FOUND} >/dev/null 2>&1 &" >>/etc/crontab
		fi
	else
		return_value 21
	fi


# Create a hidden "yes" file to pipe into the shutdown -t command
	echo "yes" > /tmp/.bootme

# Resetting bootme log dir
	[ -d ${HTX_BOOTME_LOG_DIR} ] && rm -rf ${HTX_BOOTME_LOG_DIR}
	mkdir -p ${HTX_BOOTME_LOG_DIR}
	> ${HTX_BOOTME_LOG_DIR}/htxerr.bootme

# Log bootme on
	echo >> $BOOTME_LOG_FILE
	echo "`date +\"%D %T\"`: bootme on" >> ${BOOTME_LOG_FILE}
	echo "`date +\"%D %T\"`: bootme session started" >> ${BOOTME_LOG_FILE}
	echo "crontab: $REBOOT * * * $bootmeStuff" >> ${BOOTME_LOG_FILE}
}

###############################################################################


###############################################################################
htxd_bootme_off ()
{
	CRONENTRY="`cat /etc/crontab | grep bootme`"
	if [ "$CRONENTRY" == ""  ]; then
		return_value 32;
	fi

# remove crontab entry
	[ -e /etc/crontab.ORIG ] && cp /etc/crontab.ORIG /etc/crontab 

# Remore HTXD bootme flag file
	[ -e ${HTX_HOME_DIR}/.htxd_autostart ] && rm -f ${HTX_HOME_DIR}/.htxd_autostart || return_value 31;

# Remove the hidden "yes" file for the shutdown -t command
	[ -e /tmp/.bootme ] && rm -f /tmp/.bootme
  
# Remove copies of htxerr.bootme
	[ -e ${HTX_LOG_DIR}/htxerr.bootme1 ] && rm ${HTX_LOG_DIR}/htxerr.bootme1
	[ -e ${HTX_LOG_DIR}/htxerr.bootme2 ] && rm ${HTX_LOG_DIR}/htxerr.bootme2

# Remove bootme mdt dump files
    rm -rf ${HTX_HOME_DIR}/mdt/*-htxd_bootme 2 > /dev/null

# Log bootme off
	echo "`date +\"%D %T\"`: bootme off" >> ${BOOTME_LOG_FILE}
	echo "`date +\"%D %T\"`: bootme session ended" >> ${BOOTME_LOG_FILE}
	echo >> ${BOOTME_LOG_FILE}
}
###############################################################################


###############################################################################
htxd_bootme_status ()
{
	CRONENTRY="`cat /etc/crontab | grep bootme`"
	if [ "$CRONENTRY" == ""  ]; then
		return_value 41;
	fi

	[ ! -e ${HTX_HOME_DIR}/.htxd_autostart ] && return_value 42;

}
###############################################################################


###############################################################################
htxd_bootme_net ()
{
	bootme_mdt_name_path=`cat ${HTX_HOME_DIR}/.htxd_autostart | awk '{print $1}' `
	is_net_device_present=`grep hxecom ${bootme_mdt_name_path}-htxd_bootme | wc -l 2>/dev/null`
	bootme_mdt_name=`echo ${bootme_mdt_name_path} | xargs basename`
	[ ${is_net_device_present} -ne 0 ] && { ${HTX_HOME_DIR}/etc/scripts/mdt_net ${bootme_mdt_name}; }
}
###############################################################################


###############################################################################
check_space ()
{
	SpaceAvail=`df -P -k $1 | tail -1 | awk '{print $4}'`
	SpaceAvail=$((SpaceAvail/1024))
	[ $SpaceAvail -lt $2 ] && { echo "Insufficient space in $1 (needed $2 MB, have $SpaceAvail MB" >> ${BOOTME_LOG_FILE} ; return_value 2; }
}
###############################################################################


###############################################################################
# main
###############################################################################

if [ "${HTX_HOME_DIR}" = "" ] ; then
	usage
fi

# setting bootme log file
	BOOTME_LOG_FILE="${HTX_BOOTME_LOG_DIR}/bootme.log"

# pulls REBOOT statement from ${HTX_HOME_DIR}/rules/reg/bootme/default
	rules=${HTX_HOME_DIR}/rules/reg/bootme/default
	if [ "$3" == "1" ] ; then
		REBOOT="0,20,40 *"
	elif [ "$3" == "2" ] ; then
		REBOOT="0,30 *"
	elif [ "$3" == "3" ] ; then
		REBOOT="0 *"
	elif [ "$3" == "4" ] ; then
		REBOOT="0 0"; 
	else
		REBOOT=$(grep "^REBOOT:" $rules | head -n1)
		REBOOT=${REBOOT##*: }
		[ -z "$REBOOT" ] && { echo "Please check the value of REBOOT in: $rules" >> ${BOOTME_LOG_FILE} ; return_value 11; }
	fi


# checks BOOT_CMD statement from $rules
	if [ "$2" == "10" ] ; then
		BOOT_CMD_FOUND="reboot"
	elif [ "$2" == "15" ] ; then
		BOOT_CMD_FOUND="reboot -f"
	elif [ "$2" == "20" ] ; then
		BOOT_CMD_FOUND="shutdown"
	elif [ "$2" == "25" ] ; then
		BOOT_CMD_FOUND="shutdown -f"
	else
		BOOT_CMD=$(grep "^BOOT_CMD:" $rules | head -n1)
		BOOT_CMD=${BOOT_CMD##*: }
		[ -z "$BOOT_CMD" ] && { echo "Please check the value of BOOT_CMD in: $rules" >> ${BOOTME_LOG_FILE} ; return_value 12; }
	fi

# checks BOOT_WAIT statement from $rules
	BOOT_WAIT=$(grep "^BOOT_WAIT:" $rules | head -n1 | awk '{ print $2 }')
	[ -z "$BOOT_WAIT" ] && { echo "Please check the value of BOOT_WAIT in: $rules" >> ${BOOTME_LOG_FILE} ; return_value 13; }

# select action
case $1 in

	on) htxd_bootme_on ;;

	off) htxd_bootme_off ;;

	status) htxd_bootme_status ;;

	net) htxd_bootme_net ;;	

	*) usage ;;
esac

sync;
return_value 0

###############################################################################
