#!/bin/bash

# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# 		 http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# IBM_PROLOG_END_TAG


unset NOSAVE ECGFILE g_flag save_flag warning_flag STRESS shutdown_flag is_running run_flag no_stxclient

[ "$HTX_HOME_DIR" ] || {
   install_path=`cat /var/log/htx_install_path`
   if [ -f ${install_path}/etc/scripts/htx_env.sh ]; then
       . ${install_path}/etc/scripts/htx_env.sh
   else
      echo "/var/log/htx_install_path file is supposed to have HTX install directoy path."
      echo "Either file is empty or does not contain correct install path. Hence exiting..."
      exit
   fi
}

export HTXD_STARTUP_MODE=ON
export HTX_EEH_OFF=TRUE
export HTXKDBLEVEL=1
export PATH=$PATH:${HTXBIN}:${HTXETC}/scripts_stx:${HTXSCRIPTS}

unset NOSAVE ECGFILE g_flag save_flag warning_flag STRESS shutdown_flag run_flag no_stxclient

ulimit -c unlimited
          
. ${HTX_HOME_DIR}/.bash_profile

cd ${HTX_HOME_DIR}/bin
#pwd

sync; sync
     
NSEM_WANTED=25000
PROC_SEM_FILE=/proc/sys/kernel/sem
NSEM=`cat $PROC_SEM_FILE | cut -f1`
if [ $NSEM -lt $NSEM_WANTED ]; then
	echo $NSEM_WANTED > $PROC_SEM_FILE
fi
     
echo "Starting HTX Daemon... "
echo "${HTXBIN}/htxd > ${HTX_LOG_DIR}/daemon_log 2>&1"
	${HTXBIN}/htxd 
sleep 2

