#!/bin/bash

# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# 		 http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# IBM_PROLOG_END_TAG



if [ "${HTX_HOME_DIR}" = "" ] ; then
	if [ -f /var/log/htx_install_path ] ; then
		HTX_HOME_DIR=`cat /var/log/htx_install_path`
		if [ -f ${HTX_HOME_DIR}/.htx_profile ] ; then
			export HTX_HOME_DIR;
		else
			echo "HTX_HOME_DIR is not set."
			echo "To fix this issue, export environment variable HTX_HOME_DIR with value as HTX installation directory"
			echo "export HTX_HOME_DIR=<htx_install_directory> , where <htx_install_directory> is the HTX installed path"
			echo "eg: export HTX_HOME_DIR=/usr/lpp/htx"
			echo "exiting..."
			exit 1
		fi
	else
		echo "HTX_HOME_DIR is not set."
		echo "To fix this issue, export environment variable HTX_HOME_DIR with value as HTX installation directory"
		echo "export HTX_HOME_DIR=<htx_install_directory> , where <htx_install_directory> is the HTX installed path"
		echo "eg: export HTX_HOME_DIR=/usr/lpp/htx"
		echo "exiting..."
		exit 2
	fi
else
	if [ ! -f ${HTX_HOME_DIR}/.htx_profile ] ; then
		echo "HTX_HOME_DIR is set as <${HTX_HOME_DIR}>, and the path set <${HTX_HOME_DIR}> is not HTX installed directory"
		echo "To fix this, export environment variable HTX_HOME_DIR with value as HTX installation directory"
		echo "export HTX_HOME_DIR=<htx_install_directory> , where <htx_install_directory> is the HTX installed path"
		echo "eg: export HTX_HOME_DIR=/usr/lpp/htx"
		echo "exiting..."
		exit 2
	fi
		
fi

unset NOSAVE ECGFILE g_flag save_flag warning_flag STRESS shutdown_flag is_running run_flag no_stxclient

export HTXD_STARTUP_MODE=ON
export HTXEEH=0
export HTX_EEH_OFF=TRUE
export HTXEEHRETRIES=5
export HTXKDBLEVEL=1
export PATH=$PATH:${HTX_HOME_DIR}/bin:${HTX_HOME_DIR}/etc/scripts_stx:${HTX_HOME_DIR}/etc/scripts
[ `cat /proc/cpuinfo | grep -i qemu | grep -v grep | wc -l` -ne 0 ] && export DAPL_GLOBAL_ROUTING=1


ulimit -c unlimited
          
. ${HTX_HOME_DIR}/etc/scripts/htx_setup.sh

echo "[HTX=`[ -f ${HTX_HOME_DIR}/etc/version ] && cat ${HTX_HOME_DIR}/etc/version 2>/dev/null || rpm -qa 2>/dev/null | grep htx`]  [Linux Kernel=`uname -r`]" > ${HTX_HOME_DIR}/htxlinuxlevel_info 

cd ${HTX_HOME_DIR}/bin

sync; sync
     
NSEM_WANTED=25000
PROC_SEM_FILE=/proc/sys/kernel/sem
NSEM=`cat $PROC_SEM_FILE | cut -f1`
if [ $NSEM -lt $NSEM_WANTED ]; then
	echo $NSEM_WANTED > $PROC_SEM_FILE
fi
     
mkdir -p ${HTX_LOG_DIR}/htxd
echo "Starting HTX Daemon... "
echo "${HTX_HOME_DIR}bin/htxd > ${HTX_LOG_DIR}htxd/htxd_ouput_log 2>&1"
	${HTX_HOME_DIR}bin/htxd > ${HTX_LOG_DIR}htxd/htxd_ouput_log 2>&1

[ $(ps -aef | grep ${HTX_HOME_DIR}bin/htxd | grep -v grep | wc -l) -eq 0 ] && echo "HTXD is exited" || echo "HTXD is started"

sleep 2

