#!/bin/bash

# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# 		 http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# IBM_PROLOG_END_TAG
#------------------------------------------------------------------------------

  if [[ -z ${HTX_HOME_DIR} ]] ; then
    htx_install_path=`cat /var/log/htx_install_path`
    if [ -f $htx_install_path/etc/scripts/htx_env.sh ]; then
        . $htx_install_path/etc/scripts/htx_env.sh
    else
        echo "/var/log/htx_install_path file is supposed to have HTX install directoy path."
        echo "Either file is empty or does not contain correct install path. Hence exiting..."
        exit 1
    fi
  fi

  OS=`uname -o`
  [ -f /etc/SuSE-release ]   && OS_VERSION=`head -n 1 /etc/SuSE-release`;
  [ -f /etc/redhat-release ] && OS_VERSION=`cat /etc/redhat-release`;
  [ -f /etc/os-release ] && {
    OS_VERSION=`awk -F \" '/^NAME=/||/^VERSION=/ {printf("%s ", $2)}' /etc/os-release`
  }
  [ -z "$OS_VERSION" ]       && OS_VERSION=`cat /etc/issue 2>/dev/null`

  KERNEL_VERSION=`uname -r`
  [ -f ${HTXETC}/version ] && HTX_VERSION=`cat ${HTXETC}/version 2>/dev/null` || HTX_VERSION=`rpm -qa 2>/dev/null | grep htx`
  HOST_NAME=`hostname`
  SERIAL_NO=`cat /proc/device-tree/system-id 2>/dev/null || echo "Not Found"`
  TYPE_MODEL_NO=`cat /proc/device-tree/model 2>/dev/null || echo "Not Found"`
  SYS_FW_LEVEL=`cat /proc/device-tree/openprom/model | cut -d ',' -f2 2>/dev/null || echo "Not Found"`

# Clear screen
[ $# -lt 1 ] && tput clear

# Display the gathered information
	                     echo "       ver 1.5.4.3 - OS, HTX, Firmware and Machine details"
                         echo

[ "$OS" ]             && echo "                           OS: $OS"
[ "$OS_VERSION" ]     && echo "                   OS Version: $OS_VERSION"
[ "$KERNEL_VERSION" ] && echo "               Kernel Version: $KERNEL_VERSION"
[ "$HTX_VERSION" ]    && echo "                  HTX Version: $HTX_VERSION" 
[ "$HOST_NAME" ]      && echo "                    Host Name: $HOST_NAME"	
[ "$SERIAL_NO" ]      && echo "            Machine Serial No: $SERIAL_NO" 
[ "$TYPE_MODEL_NO" ]  && echo "           Machine Type/Model: $TYPE_MODEL_NO" 
[ "$SYS_FW_LEVEL" ]   && echo "              System FW Level: $SYS_FW_LEVEL" 


# cat README.patch file
  [ -f ${HTX_HOME_DIR}/README.patch ] && {
     echo
     echo "Applied patches"
     echo "---------------"
     cat ${HTX_HOME_DIR}/README.patch
     echo
   }
   
