include ../../../htx.mk

TARGET= \
        default hxeocapi.readme 

.PHONY: all clean

all: ${TARGET}
	${MKDIR} ${REGRULES}/hxeocapi/
	${CP} ${TARGET} ${REGRULES}/hxeocapi/

clean:
	${RM} -rf ${REGRULES}/hxeocapi/*

