#!/bin/bash

set -e

case "$1" in
	configure)
		mkdir -p /var/log
		echo "/usr/lpp/htx" > /var/log/htx_install_path	
		[[ -f /usr/lpp/htx/etc/scripts/htx.d ]] && cp -f /usr/lpp/htx/etc/scripts/htx.d /etc/init.d
		[[ -f /bin/perl ]] || ln -s /usr/bin/perl /bin/perl
		ln -sf /usr/bin/awk /bin/awk
		ln -sf /usr/lpp/htx/bin/htxcmdline /bin/htxcmdline
		ln -sf /usr/lpp/htx/bin/htxcmdline /bin/hcl
		ln -sf /usr/lpp/htx/bin/htxscreen /bin/htxscreen
		ln -sf /usr/lpp/htx/bin/htxscreen /bin/htxmenu
		ln -sf /usr/lpp/htx/etc/scripts/ver /bin/ver

		update-rc.d htx.d defaults >/dev/null 2>&1

		nimesis_present=`ps -ef | grep nimesis | grep -v grep | wc -l`
		if [ $nimesis_present -eq 0 ] && [ ! "$DONTSTARTHTXD" = 1 ]
		then
			/etc/init.d/htx.d start > /tmp/htxd_service_log 2>&1 ;
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
		echo "$1"
	;;

	*)
		echo "postinst called with unknown argument \`\$1'" >&2
		exit 0
	;;
esac

exit 0;

